### ISSUE TITLE
Info and controls no longer showing

### ISSUE THREAD

**Issue by multigamesystem** [BillyBlaze/OctoPrint-FullScreen#40]
Seems the plugin was broken by a recent Octoprint update.

**Comment by MikeRatcliffe** [comment]
This is fixed by pull #39

**Comment by multigamesystem** [comment]
I have the latest version of Octoprint and the plugin and its still not working.  Sorry If I'm not understanding how to fix it otherwise.

**Comment by DerDressing** [comment]
Is there a solution yet? I have the same problem for months now.
